---
version: "3.8"
services:
  frontend:
    image: frontend_nginx:0.0.2
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: backend_node:0.0.1
    container_name: backend
    ports:
      - "3003:3003"
    volumes:
      - /Users/nucsemin/Desktop/Уроки/Mentoring/server/db/:/tmp/app/db/
